MyPage/urls.py
from django.urls import include, path
from .views import *

app_name = "MyPage"
urlpatterns = [
    path('', index, name='index'),
    path('story8', story8, name='story8')
    
]

Story6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MyPage.urls')),
    path('story9/',include('Story9.urls')),
]

Story9/urls.py
from django.urls import include, path
from .views import *

app_name = "Story9"
urlpatterns = [
    path('', intro, name='intro'),
    path('index', index, name='index'),
    path('logout/', lout, name="logout"),
    
]

MyPage/models.py
from django.db import models

# Create your models here.
class StatusModel(models.Model):
    status = models.CharField(max_length=300)
    date = models.CharField(max_length = 30)
    time = models.CharField(max_length=10)

Story9/models.py
from django.db import models

# Create your models here.

MyPage/forms.py
from django import forms
from .models import StatusModel
class StatusForm(forms.Form):
    status_attrs = {
        'type':'text',
        'class': 'form-control',
        'placeholder':'Update your status here..',
        'rows' : 5,
    }

    status = forms.CharField(label='Status', max_length=300,  required=True, widget=forms.TextInput(attrs=status_attrs))

MyPage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import StatusModel
from .forms import StatusForm
from datetime import datetime, timedelta

# Create your views here.
def index(request):
    response = {
        "form" : StatusForm(),
        "posts": StatusModel.objects.all()
    }

    if request.method   == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            status = form.cleaned_data['status'] 

            now = datetime.now() + timedelta(hours=7)
            day = now.strftime("%A")
            date = now.strftime("%e")
            month = now.strftime("%B")
            year = now.strftime("%Y")
            hour = now.strftime("%H")
            minute = now.strftime("%M")
            fulldate = f"{day}, {date} {month} {year}"
            time = f"{hour}:{minute} WIB"

            update = StatusModel(status = status, date = fulldate, time = time)
            update.save()
            return redirect("MyPage:index")
            
    return render(request, 'index.html', response)

def story8(request):
    return render(request, 'story8.html')
    
#def update_status(request):
    # if request.method   == 'POST':
    #     form = StatusForm(request.POST)
    #     if form.is_valid:
    #         status = form.cleaned_data['status']

    #         now = datetime.now() + timedelta(hours=7)
    #         day = now.strftime("%A")
    #         date = now.strftime("%e")
    #         month = now.strftime("%B")
    #         year = now.strftime("%Y")
    #         hour = now.strftime("%H")
    #         minute = now.strftime("%M")
    #         fulldate = f"{day}, {date} {month} {year}"
    #         time = f"{hour}:{minute} WIB"

    #         update = StatusModel(status = status, date = fulldate, time = time)
    #         update.save()

    #  return HttpResponseRedirect(reverse('MyPage:index'))

Story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'story9.html')

def intro(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/story9/index')
    else:
        form = AuthenticationForm()
    return render(request, 'intro.html', {'form': form})

def lout(request):
    logout(request)
    return redirect('/story9')

# def sup(request):
#     if request.method == "POST":
#         signform = UserCreationForm(request.POST)
#         if signform.is_valid():
#             user = signform.save()
#             return redirect('/story9')
#     else:
#         signform = UserCreationForm()
#     return render(request, 'intro.html', {'signform':signform})

MyPage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous">
        </script>
        <title> Timothy Regana Tarigan </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
                $( function() {
                $( "#accordion" ).accordion({
                collapsible: true,
                active : 'none'
                });
            } );
        </script>
        <script>
                $(document).ready(function(){
                    let isDark = false;
                    $("#theme").on("click", function(){
                        if(isDark){
                            $("body").css({backgroundColor:"white"})
                            $(".prof").css({color:"black"})
                            $(".sec").css({color:"black"})
                            $(".status").css({backgroundColor:"black"})
                            $(".desc").css({color:"white"})
                           
                            isDark = !isDark;
                        }
                        else{
                            $("body").css({backgroundColor:"black"})
                            $(".prof").css({color:"white"})
                            $(".sec").css({color:"white"})
                            $(".status").css({backgroundColor:"white"})
                            $(".desc").css({color:"black"})
                            
                            isDark = !isDark;
                        }
                    })

                    
                })
        </script>
    </head>

    <body>
        <h1 class=prof> HALO, APA KABAR?  </h1>
        
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" id="update" value="Update Status">
            </form>
            <button id="theme">Change theme</button>
        </div>
        </div>
        <div class="col-md-12">
            <p class="sec">Timeline</p>
            <div class="row">
                
                <div class="status col-md-3" >
                    {% for status in posts reversed %}
                    <p style="color:purple  ;">{{status.date}} - {{status.time}}</p>
                    <p class="desc">{{status.status}}</p><br>
                    {% endfor %}  
                </div>

                <div class="col-md-5">
                    <div id="accordion">
                        <h3 id="activity">Aktivitas</h3>
                        <div>
                            <p>
                            Gaming, membaca, musik
                            </p>
                        </div>

                        <h3 id="orgs">Pengalaman Organisasi</h3>
                        <div>
                            <p>
                                <li>Anggota OSIS SMP</li>
                                <li>Seksi dokumentasi di beberapa acara SMA</li>
                            </p>
                        </div>

                        <h3 id="achieve">Prestasi</h3>
                        <div>
                            <p>
                             uhhhhhhh
                            </p>
                        </div>
                    </div>
                </div>
                  
            </div>
        </div>  
        
    </body>
    
</html>

MyPage/templates/story8.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        
        <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous">
        </script>
        <title> Book Search </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'js/story8script.js' %}"></script>

    </head>
    <body>
        <h1 class="prof">SEARCH YOUR BOOK HERE</h1>
        <input id="input" type="text" placeholder="search..">
        <input type="submit" id="search" value="Search">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Author(s)</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody id="books">
            </tbody>
        </table>
    </body>
</html>

Story9/templates/intro.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login Page - Story 9</title>
    </head>
    <body>
        <h1 id="hello">Welcome.</h1>
        <form class="auth-form" action="{% url 'Story9:intro' %}" method="POST">
            {% csrf_token %}
            <label for="id_username">Username:</label>
            <input type="text" name="username" autofocus="" required="" id="id_uname">
            <br>
            <br>
            <label for="id_password">Password:</label>
            <input type="password" name="password" required="" id="id_pw">
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <input type="submit" id="login" value="Login">
        </form>

    </body>    
</html>

Story9/templates/story9.html
<!DOCTYPE html>
<html>
    <head>
        <h1 id="logged">Logged in!</h1>
        <title>Logged In - Story 9</title>
    </head>
    <body>
        <h1>Hello, {{ user }}</h1>
        <a href="{% url 'Story9:logout' %}">
            <button id="logout">Logout</button>
        </a>

    </body>
</html>